### ISSUE TITLE
Extra headers

### ISSUE THREAD

**Issue by TIOUK** [Smoothieware/Smoothieboard2#24]
First off, that is a great looking board, thanks for all the work.

My question is, as there appears to be room in the 2660 version of the board, is it possible to add step/dir/en/gnd headers/JST PH or similar for some or all of the driver outputs?

**Comment by arthurwolf** [comment]
Hey.

So, if we break anything out, it'll be gadgeteers like the rest of the board, not jst. We'll have gadgeteer->jst adapters anyway.
Kliment said that while it looks like there is space, that's not necessarily true on the internal layers.
I think it was decided the other day though that we'd break the pins out if we could (to gadgeteers). Stay tuned, might see a PR for this come in.

Thanks for the comments/ideas!

Cheers!

**Comment by Ccecil** [comment]
This needs to be added.  Even if it is just Step/Dir.  Planned for the next revision.
Wolfmanjm has also recently added parallel axes in config as well.

**Comment by wolfmanjm** [comment]
As this is now in firmware allowing the 4th driver to be paralleled with X,Y or Z in firmware I am closing this as H/W changes are not needed now. (Discussion welcome if there are other reasons).
