### ISSUE TITLE
Extensions template missing Gadgeteer.lib?

### ISSUE THREAD

**Issue by bobc** [Smoothieware/Smoothieboard2#4]
The template for extensions refers to "Gadgeteer.lib", but I could not find this file anywhere.

**Comment by arthurwolf** [comment]
@BillBucket does this mean you forgot a file ?

**Comment by BillBucket** [comment]
New pull request for version without reference to unused gadgeteer library. Should be vanilla in all other respects.

**Comment by bobc** [comment]
Ok, no problem. I've created a library called Gadget.lib with useful gadgeteer related things for my extensions.
